name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *" # Запуск раз в сутки
  workflow_dispatch:    # Возможность запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest
    # Важно! Добавляем разрешение на запись в репозиторий
    permissions:
      contents: write

    steps:
      # Используем последнюю стабильную версию actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Генерируем змейку с помощью последней версии Platane/snk
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Публикуем файлы в ветку 'output'
      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'chore: update snake animation'
